server:
  port: 8888

LOCAL_REPO: '@project.basedir@/../config-files'

spring:
  application:
    name: config-server
  profiles:
    active:
      - native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///${LOCAL_REPO}



