server:
  port: 8888

LOCAL_REPO: '/Users/hmohamed/github/pimco/demo-apps-config/config-server-local/../config-files'

spring:
  application:
    name: config-server
  profiles:
    active:
      - native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///${LOCAL_REPO}



